name: command-wrapper-toolset-yx
version: 0.1.0.0
synopsis: TODO
description: TODO
github: trskop/dot.config
license: BSD3
license-file: LICENSE
author: Peter Trško
maintainer: peter.trsko@gmail.com
copyright: (c) 2018-2019 Peter Trško
category: Tools

extra-source-files:
  - README.md
  - dhall/*.dhall

default-extensions:
  - DeriveFunctor
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications

dependencies:
  - base

  - case-insensitive
  - comonad
  - dhall >=1.19
  - dhall-bash
  - dhall-json
  - directory
  - endo
  - executable-path
  - filepath
  - generic-lens
  - mtl
  - optparse-applicative
  - prettyprinter
  - projectroot
  - text
  - turtle
  - unix
  - unordered-containers
  - verbosity >=0.3

  - command-wrapper
  - host-and-port
  - mainplate

ghc-options: -Wall

executables:
  yx-env:
    source-dirs: app-yx-env
    main: Main.hs
    dependencies:
      - Diff
      - ansi-terminal

      - genbashrc

  yx-path:
    source-dirs: app-yx-path
    main: Main.hs
    dependencies:
      - lens
      - process

  yx-this:
    source-dirs: app-yx-this
    main: Main.hs
    dependencies:
      - containers
      - process

  yx-new:
    source-dirs: app-yx-new
    main: Main.hs
