# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-15.6

packages:
  - '.'

extra-deps:
  - endo-0.3.0.1
  - fuzzy-0.1.0.0
  - verbosity-0.4.0.0

  - dhall-1.31.1
  - dhall-bash-1.0.29
  - dhall-json-1.6.3
  - aeson-yaml-1.0.6.0
  - prettyprinter-1.6.1

# Keeping the following in case of new Dhall release:
  # Dhall dependencies:
# - dotgen-0.4.2@sha256:309b7cc8a3593a8e48bee7b53020d5f72db156d58edf78a0214f58fbb84b292b
# - serialise-0.2.1.0@sha256:8d6051f64c6ebfaf705195dd0b8dfb667617f2e674b290ed2e44985009e4f951
# - megaparsec-7.0.4
# - repline-0.2.0.0
# - neat-interpolation-0.3.2.4  # dhall-bash

  - lock-file-0.7.0.0

  - git: https://github.com/trskop/host-and-port.git
    commit: e934d338b8ba6b5ce6c0e16e1d1a46d2d5099808

  - git: https://github.com/trskop/mainplate.git
    commit: 118acdb919e7bd7aaa07e7554a2d1eabde86acf5

  - git: https://github.com/trskop/open-in-editor.git
    commit: eec72c9c99fd8bd89866bdd85a23343a4a6fbae8

  - git: https://github.com/trskop/command-wrapper.git
    subdirs:
      - command-wrapper-core
      - command-wrapper-subcommand
      - command-wrapper
    commit: e64ae8f463a75256b316b039652cc1364c9cd088 # rc8 with Dhall 1.31.1

  - git: https://github.com/trskop/genbashrc.git
    commit: 87edf5f77320d716a39376b6a0e210ab46802ff4

flags:
  verbosity:
    dhall: true

  host-and-port:
    dhall: true
    generic-lens: true
