# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/peter/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: ghc-8.10.4
#resolver: lts-18.5
packages: []

#extra-deps: []
#flags: {}

#extra-package-dbs: []
